# Default values for phoenix-authorization-api
# This file is in YAML format
# Declared variables to be passed into $/templates files

namespace: phoenix-prod

image:
  repository: 988207228673.dkr.ecr.eu-central-1.amazonaws.com/phoenix-authorization-api
  tag: prod
  pullPolicy: Always

imagePullSecrets: []

service:
  type: NodePort
  port: 80

ingress:
  external:
    sslRedirect: "false"
    forceSslRedirect: "false"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

# replicacount has no impact if autoscaling.enabled = true
replicacount: 1
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 85

dns:
  internal: prod.sgp.private.wiley.host
  external: prod.sgp.wiley.host

env_vars:
  data:
    LOG_JSON: "true"
    LOG_MINIMUMLEVEL: Information
    MONGO_DB_NAME: authorization-api
    MONGO_TLS_CA_FILE_PATH: "/cert/global-bundle.pem"
    USERS_API_BASE_URL: "http://users-api"
    COMPANY_API_BASE_URL: "http://company-api"
    ENTITLEMENTS_API_BASE_URL: "http://entitlements-api"
    GROUPS_API_BASE_URL: "http://groups-api"

externalsecrets:
  refreshInterval: 1m
  secretCreationPolicy: Owner
  secretStoreName: eks-prod-eu-secret-manager
  secretStoreType: ClusterSecretStore
  data:
  - keyValue: eks/phoenix
    nameValue: USERS_API_KEY
    propertyValue: USERS_API_KEY
  - keyValue: eks/phoenix
    nameValue: COMPANY_API_KEY
    propertyValue: COMPANY_API_KEY
  - keyValue: eks/phoenix
    nameValue: ENTITLEMENTS_API_KEY
    propertyValue: ENTITLEMENTS_API_KEY
  - keyValue: eks/phoenix
    nameValue: MONGO_CONNECTION_STRING
    propertyValue: AUTHORIZATION_API_PROD_MONGO_CONNECTION_STRING
  - keyValue: eks/phoenix
    nameValue: GROUPS_API_KEY
    propertyValue: GROUPS_API_KEY
  - keyValue: eks/phoenix
    nameValue: API_KEY
    propertyValue: AUTHORIZATION_API_KEY
