version: '3.8'

services:
  authorization-api:
    container_name: authorization-api
    build:
        context: .
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOG_JSON=true
      - LOG_MINIMUMLEVEL=Information
      - MONGO_DB_NAME=authorization-api
      - API_KEY=Secret
      - USERS_API_BASE_URL=http://users-api:50103
      - USERS_API_KEY=
      - COMPANY_API_BASE_URL=http://company-api
      - COMPANY_API_KEY=Secret
      - ENTITLEMENTS_API_BASE_URL=http://entitlements-api
      - ENTITLEMENTS_API_KEY=Secret
      - GROUPS_API_BASE_URL=http://groups-api
      - GROUPS_API_KEY=
      - MONGO_CONNECTION_STRING=mongodb://root:root@mongodb:27017
    working_dir: /app
    volumes:
      - "..:/app"
      - "/app/run"
    entrypoint: "/app/run/entrypoint.dev.sh"
    ports:
      - "50114:80"

networks:
  default:
    name: PL_AUTOMATION-network
    external: true